module_blackjack = "BlackJack"
msg_bj_shuffle = "The dealer is shuffling the cards."
bj_hand = '%s cards: %s'
bj_no_cards = 'no cards.'
bj_points = 'points'
bj_credits = "Credits"

#########
# Reset #
#########
mt_blackjack_reset = "Reset"
md_blackjack_reset = "Reset your blackjack game."
msg_bj_reset = "Your BlackJack credits have been reset. Balance: %s."

#######
# Bet #
#######
mt_blackjack_bet = "Bet on BlackJack"
md_blackjack_bet = "Bet on a new BlackJack game."
err_bj_running = "You are already playing a game."
err_bj_min_bet = "You have to bet at least %d."
err_bj_credits = "You do only have %d credits."
msg_bj_started = "You bet %d and have %d left. You hold %s and the dealer got %s."
msg_bj_started_bj = "You bet %d... and got %s, BlackJack! You win %d and now have %d."

########
# Draw #
########
mt_blackjack_draw = "Draw Cards"
md_blackjack_draw = "Draw one or more cards in your current blackjack game."
err_bj_not_running = "You have to bj.bet first."
msg_bj_draw_bj = "You draw %d card(s) and now have %s. BlackJack! You win %d and now have %d."
msg_bj_draw_won = "You draw %d card(s) and now have %s. You win %d and now have %d."
msg_bj_drawn = "You draw %d card(s) and now hold %s."
msg_bj_busted = "You draw %d card(s) and now hold %s. Busted! You lose your %d and now have %d."

########
# Hold #
########
mt_blackjack_hold = "Hold"
md_blackjack_hold = "Stop drawing cards and let the dealer play blackjack."
msg_bj_won = "The dealer draws %s. You win %d and now have %d"
msg_bj_lost = "The dealer draws %s. You lost your %d and now have %d."
msg_bj_lost_draw = "The dealer draws %s. Draw! You get your %d back and have %d again."

########
# Site #
########
mt_blackjack_site = "BlackJack"
md_blackjack_site = "HTTP combined view for playing BlackJack on this PyGDOv8 installation."
info_blackjack = "You have played %d games and won %d (%.0f%%). Balance: %dc. You hold %s and the dealer holds %s. When you have %d credits you can leave."
btn_bet = "Bet"
btn_draw_card = "Draw Card"
btn_hold_cards = "Hold"
btn_reset = "Reset"
btn_leave = "Leave"

#########
# Leave #
#########
mt_blackjack_leave = "Leave Table"
md_blackjack_leave = "Collect your wins for the wechall blackjack challenge."
err_bj_millionaire = "To leave the table for the challenge you need %d credits. You have only %d so %d are missing."
msg_bj_millionaire = "You have more than %d and leave the table with your solution: %s"

#########
# Stats #
#########
